package cls

import (
	"context"
	"github.com/tencentcloud/steampipe-plugin-tencentcloud/tencentcloud/utils"
	"time"

	cls "github.com/tencentcloud/tencentcloud-sdk-go-intl-en/tencentcloud/cls/v20201016"
	"github.com/turbot/steampipe-plugin-sdk/v5/grpc/proto"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin"
	"github.com/turbot/steampipe-plugin-sdk/v5/plugin/transform"
)

// Table Definition

func TableTencentcloudClsMachineGroup() *plugin.Table {
	return &plugin.Table{
		Name:              "tencentcloud_cls_machine_group",
		Description:       "Tencent Cloud CLS machine groups are collections of machines (by IP or label) that the LogListener agent runs on; a group defines how its members collect and ship logs to CLS topics.",
		GetMatrixItemFunc: buildClsRegionList,
		List: &plugin.ListConfig{
			KeyColumns: []*plugin.KeyColumn{
				{Name: "machine_group_id", Require: plugin.Optional},
				{Name: "machine_group_name", Require: plugin.Optional},
			},
			Hydrate: listClsMachineGroups,
			Tags:    map[string]string{"service": "cls", "action": "DescribeMachineGroups"},
		},
		Get: &plugin.GetConfig{
			KeyColumns: plugin.SingleColumn("machine_group_id"),
			Hydrate:    getClsMachineGroup,
			Tags:       map[string]string{"service": "cls", "action": "DescribeMachineGroups"},
		},
		Columns: utils.WithCommonColumns([]*plugin.Column{
			{Name: "machine_group_id", Type: proto.ColumnType_STRING, Description: "The unique ID of the machine group.", Transform: transform.FromField("GroupId")},
			{Name: "machine_group_name", Type: proto.ColumnType_STRING, Description: "The name of the machine group.", Transform: transform.FromField("GroupName")},
			{Name: "os_type", Type: proto.ColumnType_INT, Description: "The operating system type of the machine group (0: Linux, 1: Windows).", Transform: transform.FromField("OSType")},
			{Name: "machine_group_type", Type: proto.ColumnType_STRING, Description: "The machine group type (ip: values are machine IPs, label: values are machine tags).", Transform: transform.FromField("MachineGroupType")},
			{Name: "machine_group_values", Type: proto.ColumnType_JSON, Description: "The list of IP addresses or labels in the machine group, depending on the group type.", Transform: transform.FromField("MachineGroupValues")},
			{Name: "auto_update", Type: proto.ColumnType_STRING, Description: "Whether machine group auto-update is enabled.", Transform: transform.FromField("AutoUpdate")},
			{Name: "update_start_time", Type: proto.ColumnType_STRING, Description: "The start time of the LogListener upgrade window (HH:mm:ss).", Transform: transform.FromField("UpdateStartTime")},
			{Name: "update_end_time", Type: proto.ColumnType_STRING, Description: "The end time of the LogListener upgrade window (HH:mm:ss).", Transform: transform.FromField("UpdateEndTime")},
			{Name: "service_logging", Type: proto.ColumnType_BOOL, Description: "Whether service logs are enabled to record logs generated by the LogListener service itself.", Transform: transform.FromField("ServiceLogging")},
			{Name: "delay_cleanup_time", Type: proto.ColumnType_INT, Description: "The regular cleanup time in days for offline machines in the group (default 30).", Transform: transform.FromField("DelayCleanupTime")},
			{Name: "meta_tags", Type: proto.ColumnType_JSON, Description: "The metadata tags attached to the machine group as a map of key -> value.", Transform: transform.FromField("MetaTags")},
			{Name: "create_time", Type: proto.ColumnType_TIMESTAMP, Description: "The creation time of the machine group.", Transform: transform.FromField("CreateTime").NullIfZero()},
			{Name: "tags", Type: proto.ColumnType_JSON, Description: "The tags attached to the machine group as a map of key -> value.", Transform: transform.FromField("Tags")},
			{Name: "region", Type: proto.ColumnType_STRING, Description: "The region where the machine group resides.", Transform: transform.FromField("Region")},
			{Name: "title", Type: proto.ColumnType_STRING, Description: "Title of the resource.", Transform: transform.FromField("GroupName")},
			{Name: "akas", Type: proto.ColumnType_JSON, Description: "Array of globally unique identifier strings (also known as) for the resource.", Transform: transform.FromField("Akas")},
		}),
	}
}

// List Function

func listClsMachineGroups(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (any, error) {
	plugin.Logger(ctx).Debug("listClsMachineGroups", "region", d.EqualsQualString(utils.MatrixKeyRegion), "quals", d.EqualsQuals)

	client := &cls.Client{}
	if err := utils.InitClient(ctx, d, client); err != nil {
		plugin.Logger(ctx).Error("listClsMachineGroups", "client_init_error", err)
		return nil, err
	}

	region := d.EqualsQualString(utils.MatrixKeyRegion)

	filters := buildClsMachineGroupFilters(d.EqualsQuals)

	pageSize := utils.PageSizeFromLimit(d, 100, 1)
	var offset int64

	for {
		d.WaitForListRateLimit(ctx)

		req := cls.NewDescribeMachineGroupsRequest()
		req.Offset = &offset
		req.Limit = &pageSize
		if len(filters) > 0 {
			req.Filters = filters
		}

		utils.LogRequest(ctx, "listClsMachineGroups", req)
		resp, err := client.DescribeMachineGroupsWithContext(ctx, req)
		if err != nil {
			plugin.Logger(ctx).Error("listClsMachineGroups", "request_error", err)
			return nil, err
		}
		if resp == nil || resp.Response == nil {
			break
		}

		items := resp.Response.MachineGroups
		for _, item := range items {
			if item == nil {
				continue
			}
			row := toClsMachineGroupRow(item)
			row.Region = region
			d.StreamListItem(ctx, row)
			if d.RowsRemaining(ctx) == 0 {
				return nil, nil
			}
		}
		total := utils.PtrInt64(resp.Response.TotalCount)
		if utils.PageDone(offset, int64(len(items)), total) {
			break
		}
		offset += int64(len(items))
	}

	return nil, nil
}

func buildClsMachineGroupFilters(equalsQuals plugin.KeyColumnEqualsQualMap) []*cls.Filter {
	return utils.BuildFilters(equalsQuals, newClsFilter,
		utils.FilterMapping{QualName: "machine_group_id", FilterName: "machineGroupId"},
		utils.FilterMapping{QualName: "machine_group_name", FilterName: "machineGroupName"},
	)
}

// Get Function

func getClsMachineGroup(ctx context.Context, d *plugin.QueryData, _ *plugin.HydrateData) (any, error) {
	groupId := d.EqualsQuals["machine_group_id"].GetStringValue()
	plugin.Logger(ctx).Info("getClsMachineGroup", "machine_group_id", groupId, "region", d.EqualsQualString(utils.MatrixKeyRegion))

	client := &cls.Client{}
	if err := utils.InitClient(ctx, d, client); err != nil {
		plugin.Logger(ctx).Error("getClsMachineGroup", "client_init_error", err)
		return nil, err
	}

	if groupId == "" {
		return nil, nil
	}

	region := d.EqualsQualString(utils.MatrixKeyRegion)

	req := cls.NewDescribeMachineGroupsRequest()
	req.Filters = []*cls.Filter{newClsFilter("machineGroupId", groupId)}

	utils.LogRequest(ctx, "getClsMachineGroup", req)
	resp, err := client.DescribeMachineGroupsWithContext(ctx, req)
	if err != nil {
		plugin.Logger(ctx).Error("getClsMachineGroup", "request_error", err)
		return nil, err
	}
	if resp == nil || resp.Response == nil || len(resp.Response.MachineGroups) == 0 {
		return nil, nil
	}

	row := toClsMachineGroupRow(resp.Response.MachineGroups[0])
	row.Region = region
	return row, nil
}

// Row Type

type clsMachineGroupRow struct {
	GroupId            string
	GroupName          string
	OSType             uint64
	MachineGroupType   string
	MachineGroupValues []string
	AutoUpdate         string
	UpdateStartTime    string
	UpdateEndTime      string
	ServiceLogging     bool
	DelayCleanupTime   int64
	MetaTags           map[string]string
	CreateTime         *time.Time
	Tags               map[string]string
	Region             string
	Akas               []string
}

func toClsMachineGroupRow(m *cls.MachineGroupInfo) clsMachineGroupRow {
	row := clsMachineGroupRow{
		GroupId:          utils.PtrString(m.GroupId),
		GroupName:        utils.PtrString(m.GroupName),
		OSType:           utils.PtrUint64(m.OSType),
		AutoUpdate:       utils.PtrString(m.AutoUpdate),
		UpdateStartTime:  utils.PtrString(m.UpdateStartTime),
		UpdateEndTime:    utils.PtrString(m.UpdateEndTime),
		ServiceLogging:   utils.PtrBool(m.ServiceLogging),
		DelayCleanupTime: utils.PtrInt64(m.DelayCleanupTime),
		MetaTags:         metaTagsToMap(m.MetaTags),
		CreateTime:       utils.ParseTimestamp(m.CreateTime),
		Tags:             TagsToMap(m.Tags),
	}

	// UpdateStartTime/UpdateEndTime are time-only strings (HH:mm:ss) and are
	// exposed as STRING columns rather than parsed into *time.Time.
	if m.MachineGroupType != nil {
		row.MachineGroupType = utils.PtrString(m.MachineGroupType.Type)
		row.MachineGroupValues = utils.PtrStringSlice(m.MachineGroupType.Values)
	}

	if row.GroupId != "" {
		row.Akas = []string{"tencentcloud:cls:machine-group:" + row.GroupId}
	}
	return row
}

// metaTagsToMap converts a []*cls.MetaTagInfo (Key/Value) to a map. CLS machine
// groups carry both resource Tags (managed via Tag API) and MetaTags (machine
// metadata); MetaTags use the MetaTagInfo shape, so they need a local converter
// rather than reusing the module-level TagsToMap.
func metaTagsToMap(tags []*cls.MetaTagInfo) map[string]string {
	if len(tags) == 0 {
		return nil
	}
	out := make(map[string]string, len(tags))
	for _, t := range tags {
		if t == nil {
			continue
		}
		k := utils.PtrString(t.Key)
		if k == "" {
			continue
		}
		out[k] = utils.PtrString(t.Value)
	}
	if len(out) == 0 {
		return nil
	}
	return out
}
